#%RAML 0.8
title: 易邦生物
baseUri: http://localhost:80/web
version: v0.1
mediaType: application/json

traits:
  # 响应成功
  - resSuccess:
      responses:
        200:
          description: 成功
          body:
            application/json:
              schema: |
                {
                  "$schema": "http://json-schema.org/draft-04/schema#",
                  "id": "http://jsonschema.net",
                  "type": "object",
                  "properties": {
                    "code": {
                      "id": "http://jsonschema.net/code",
                      "type": "integer"
                    },
                    "msg": {
                      "id": "http://jsonschema.net/msg",
                      "type": "string"
                    }
                  },
                  "required": [
                    "code",
                    "msg"
                  ]
                }
              example: |
                {
                  "code" : 0,
                  "msg" : "成功"
                }
  # 响应成功2
  - resSuccess2:
      responses:
        200:
          description: 成功
          body:
            application/json:
              schema: |
                {
                  "$schema": "http://json-schema.org/draft-04/schema#",
                  "id": "http://jsonschema.net",
                  "type": "object",
                  "properties": {
                    "code": {
                      "id": "http://jsonschema.net/code",
                      "type": "integer"
                    },
                    "msg": {
                      "id": "http://jsonschema.net/msg",
                      "type": "string"
                    }
                  },
                  "required": [
                    "code",
                    "msg"
                  ]
                }
              example: |
                {
                  "code" : "9",
                  "msg" : "success"
                }
              
  # 查询成功
  - queryParam:
      queryParameters:
        nickname:
          displayName: nickname
          description: 昵称
          required: false
          type: string
          minLength: 3
          maxLength: 60
          example: 花落莫离
        registDate:
          displayName: registDate
          description: 注册日期
          required: false
          type: date
          example: 2001-02-03 04:05:06
        age:
          displayName: age
          description: 年龄
          required: false
          type: integer
          minimum: 16
          maximum: 80
          example: 20
        manager:
          displayName: manager
          description: 是否是管理员
          required: true
          type: boolean
          example: false
        
  # 表单参数
  - formParam:
      body:
        application/x-www-form-urlencoded:
          formParameters:
            nickname:
              displayName: nickname
              description: 昵称
              required: false
              type: string
              minLength: 3
              maxLength: 60
              example: 花落莫离
            registDate:
              displayName: registDate
              description: 注册日期
              required: false
              type: date
              example: 2001-02-03 04:05:06
            age:
              displayName: age
              description: 年龄
              required: false
              type: integer
              minimum: 16
              maximum: 80
              example: 20
            manager:
              displayName: manager
              description: 是否是管理员
              required: false
              type: boolean
              example: false
              
#####################################################################
############################## URI ##################################
#####################################################################

/api/uri:
  displayName: uri
  description: URI参数转
  
  get:
    description: get请求,没有参数
    is:
      - resSuccess:
  /queryParam:
    get:
      description: get请求,query参数
      queryParameters:
        nickname:
          displayName: nickname
          description: 昵称
          required: false
          type: string
          minLength: 3
          maxLength: 60
          example: 花落莫离
        registDate:
          displayName: registDate
          description: 注册日期
          required: false
          type: date
          example: 2001-02-03 04:05:06
        age:
          displayName: age
          description: 年龄
          required: false
          type: integer
          minimum: 16
          maximum: 80
          example: 20
        manager:
          displayName: manager
          description: 是否是管理员
          required: false
          type: boolean
          example: false
      is:
        - resSuccess:
          
  /info/{username}/{token}:
    uriParameters:
      username:
        displayName: username
        description: 用户名 
        required: true
        type: string
        minLength: 3
        maxLength: 20
        example: hualuomoli
      token:
        displayName: token
        description: 令牌
        required: true
        type: string
        example: 51b45c0c38804df6bcee1d8a0422ae2e
    get:
      description: get请求,uri参数
      is:
        - resSuccess:
  /msg:
    get:
      description: get请求,query参数
      is: 
        - queryParam:
        - resSuccess:
    post:
      description: post请求,form参数
      is:
        - formParam:
        - resSuccess2:
  
  /list/{username}/{token}/{pageNo}/{pageSize}:
    uriParameters:
      username:
        displayName: username
        description: 用户名 
        required: true
        type: string
        minLength: 3
        maxLength: 20
        example: hualuomoli
      token:
        displayName: token
        description: 令牌
        required: true
        type: string
        example: 51b45c0c38804df6bcee1d8a0422ae2e
      pageNo:
        displayName: pageNo
        description: 当前页面
        required: false
        type: integer
        minimum: 1
        maximum: 100
        example: 1
      pageSize:
        displayName: pageSize
        description: 每页数据
        required: false
        type: integer
        minimum: 10
        maximum: 50
        example: 20
    get:
      description: get 请求,URI和query参数
      is:
        - queryParam:
        - resSuccess:
    post:
      description: post请求,uri和form参数
      is:
        - formParam:
        - resSuccess2:
  
 