#%RAML 0.8
title: 易邦生物
baseUri: http://localhost:80/web
version: v0.1
mediaType: application/json


/api/response:
  displayName: response
  description: 响应
  
  /noResponse:
    get:
      description: 没有返回信息
  /nodata:
    get:
      description: 没有数据,只有响应编码和响应信息
      responses:
        200:
          description: 处理成功
          body:
            application/json:
              schema: |
                {
                  "$schema": "http://json-schema.org/draft-04/schema#",
                  "id": "http://jsonschema.net",
                  "type": "object",
                  "properties": {
                    "code": {
                      "id": "http://jsonschema.net/code",
                      "type": "integer"
                    },
                    "msg": {
                      "id": "http://jsonschema.net/msg",
                      "type": "string"
                    }
                  },
                  "required": [
                    "code",
                    "msg"
                  ]
                }
              example: |
                {
                  "code" : 0,
                  "msg" : "处理成功"
                }
  /mapData:
    get:
      description: 返回的data为object
      responses:
        200:
          description:
          body:
            application/json:
              schema: |
                {
                  "$schema": "http://json-schema.org/draft-04/schema#",
                  "id": "http://jsonschema.net",
                  "type": "object",
                  "properties": {
                    "code": {
                      "id": "http://jsonschema.net/code",
                      "type": "integer"
                    },
                    "msg": {
                      "id": "http://jsonschema.net/msg",
                      "type": "string"
                    },
                    "data": {
                      "id": "http://jsonschema.net/data",
                      "type": "object",
                      "properties": {
                        "name": {
                          "id": "http://jsonschema.net/data/name",
                          "type": "string"
                        },
                        "price": {
                          "id": "http://jsonschema.net/data/price",
                          "type": "number"
                        },
                        "amount": {
                          "id": "http://jsonschema.net/data/amount",
                          "type": "integer"
                        },
                        "def": {
                          "id": "http://jsonschema.net/data/def",
                          "type": "boolean"
                        },
                        "time": {
                          "id": "http://jsonschema.net/data/time",
                          "type": "string"
                        }
                      },
                      "required": [
                        "name",
                        "price",
                        "amount"
                      ]
                    }
                  },
                  "required": [
                    "code",
                    "msg",
                    "data"
                  ]
                }
              example: |
                {
                  "code" : 0,
                  "msg" : "处理成功",
                  "data" : {
                    "name" : "Ipad 64G",
                    "price" : 3200.15,
                    "amount": 10,
                    "def" : false,
                    "time" : "2015-01-02 15:23:48"
                  }
                }
                
  /listData:
    get:
      description: 返回list
      responses:
        200:
          description: 
          body:
            application/json:
              schema: |
                {
                  "$schema": "http://json-schema.org/draft-04/schema#",
                  "id": "http://jsonschema.net",
                  "type": "object",
                  "properties": {
                    "code": {
                      "id": "http://jsonschema.net/code",
                      "type": "integer"
                    },
                    "msg": {
                      "id": "http://jsonschema.net/msg",
                      "type": "string"
                    },
                    "data": {
                      "id": "http://jsonschema.net/data",
                      "type": "array",
                      "items": {
                        "id": "http://jsonschema.net/data/0",
                        "type": "object",
                        "properties": {
                          "name": {
                            "id": "http://jsonschema.net/data/0/name",
                            "type": "string"
                          },
                          "price": {
                            "id": "http://jsonschema.net/data/0/price",
                            "type": "number"
                          },
                          "amount": {
                            "id": "http://jsonschema.net/data/0/amount",
                            "type": "integer"
                          },
                          "def": {
                            "id": "http://jsonschema.net/data/0/def",
                            "type": "boolean"
                          },
                          "time": {
                            "id": "http://jsonschema.net/data/0/time",
                            "type": "string"
                          }
                        }
                      }
                    }
                  },
                  "required": [
                    "code",
                    "msg",
                    "data"
                  ]
                }
              example: |
                {
                  "code" : 0,
                  "msg": "success",
                  "data" : [
                    {
                      "name" : "Ipad 64G",
                      "price" : 3200.15,
                      "amount": 10,
                      "def" : false,
                      "time" : "2015-01-02 15:23:48"
                    }
                  ]
                }
  /pageData:
    displayName: pageData
    description: 分页
    get:
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "$schema": "http://json-schema.org/draft-04/schema#",
                  "id": "http://jsonschema.net",
                  "type": "object",
                  "properties": {
                    "code": {
                      "id": "http://jsonschema.net/code",
                      "type": "integer"
                    },
                    "msg": {
                      "id": "http://jsonschema.net/msg",
                      "type": "string"
                    },
                    "data": {
                      "id": "http://jsonschema.net/data",
                      "type": "object",
                      "properties": {
                        "total": {
                          "id": "http://jsonschema.net/data/total",
                          "type": "integer"
                        },
                        "pageNumber": {
                          "id": "http://jsonschema.net/data/pageNumber",
                          "type": "integer"
                        },
                        "pageSize": {
                          "id": "http://jsonschema.net/data/pageSize",
                          "type": "integer"
                        },
                        "productes": {
                          "id": "http://jsonschema.net/data/productes",
                          "type": "array",
                          "items": {
                            "id": "http://jsonschema.net/data/productes/1",
                            "type": "object",
                            "properties": {
                              "name": {
                                "id": "http://jsonschema.net/data/productes/1/name",
                                "type": "string"
                              },
                              "price": {
                                "id": "http://jsonschema.net/data/productes/1/price",
                                "type": "number"
                              },
                              "amount": {
                                "id": "http://jsonschema.net/data/productes/1/amount",
                                "type": "integer"
                              },
                              "def": {
                                "id": "http://jsonschema.net/data/productes/1/def",
                                "type": "boolean"
                              },
                              "time": {
                                "id": "http://jsonschema.net/data/productes/1/time",
                                "type": "string"
                              }
                            }
                          }
                        }
                      }
                    }
                  },
                  "required": [
                    "code",
                    "msg",
                    "data"
                  ]
                }
              example: |
                {
                  "code" : 0,
                  "msg" : "处理成功",
                  "data" : {
                    "total" : 100,
                    "pageNumber" : 2,
                    "pageSize" : 20,
                    "productes" : [
                      {
                        "name" : "Ipad 64G",
                        "price" : 3200.15,
                        "amount": 10,
                        "def" : false,
                        "time" : "2015-01-02 15:23:48"
                      },
                      {
                        "name" : "Ipad 64G",
                        "price" : 3200.15,
                        "amount": 10,
                        "def" : false,
                        "time" : "2015-01-02 15:23:48"
                      }
                    ]
                  }
                }