bmap:
  security: vXTj298s3IPbRKdqaAED0AU3aY3rmPyh
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/hualuomoli?useUnicode=true&characterEncoding=utf-8
  username: root
  password: ""

mybatis:
  mapperLocations: classpath*:mappers/**/*.xml
  basePackage: com.github.hualuomoli
  annotationClass: org.springframework.stereotype.Repository
  
view:
  prefix: /WEB-INF/views/
  suffix: .jsp


upload:
  maxSize: 10240000
  encoding: UTF8

static:
  resources: /static/**,/static/,31556926
  cachePeriod: 31556926
  
# spring mvc request version
version:
  name: content-version
  default: ""

filters:
  corses:
    - cors:
      allowOrigin: file://
      maxAge: 3600
      allowCredentials: true
      allowMethods: PUT,POST,GET,DELETE,OPTIONS
      allowHeaders: x-requested-with,Content-Type,*
    - cors:
      allowOrigin: "null"
    - cors:
      allowOrigin: http://localhost:3000
    - cors:
      allowOrigin: http://127.0.0.1:3000