jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/hualuomoli?useUnicode=true&characterEncoding=utf-8
  username: root
  password: ""

mybatis:
  mapperLocations: classpath*:mappers/**/*Mapper.xml
  basePackage: com.github.hualuomoli
  annotationClass: org.springframework.stereotype.Repository
  # typeHandlers:
  
  
view:
  prefix: /WEB-INF/views/
  suffix: .jsp


upload:
  maxSize: 10240000
  encoding: UTF8

resources:
  # webapp目录下
  #- resource:
  #  url: /css/**
  #  location: /css/

  # 绝对路径
  #- resource:
  #  url: /files/**
  #  location: file:E:/files/
  #- resource:
  #  url: /files/**
  #  location: file:/E:/files/
  
  # 相对项目路径
  #- resource:
  #  url: /files
  #  location: project:../files
  #- resource:
  #  url: /files
  #  location: project:./files
    
  
  # 其他网络的资源
  # http://pic.4j4j.cn/upload/pic/20130815/5e604404fe.jpg
  #- resource:
  #  url: /pic/**
  #  location: http://pic.4j4j.cn/upload/pic/
  
  - resource:
    url: /files
    location: project:../files
  
    
# 应用
application:
  # 项目访问URL
  serverUrl: ""
  staticFiles:
    - staticFile:
      name: files
      url: /files
      location: project:../files
    
filter:
  # cors server
  cors:
    servers:
      - server:
        allowOrigin: http://localhost:3000/
      - server:
        allowOrigin: file://
  
# spring mvc request version
restful:
  version:
    name: api-version
    default: ""

# 安全
digest:
  # 密码
  password:
    algorithm: sha1
    saltNumber: 8
    iterations: 10