jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/hualuomoli?useUnicode=true&characterEncoding=utf-8
  username: root
  password: ""

mybatis:
  mapperLocations: classpath*:mappers/**/*.xml
  basePackage: com.github.hualuomoli
  annotationClass: org.springframework.stereotype.Repository
  
view:
  prefix: /WEB-INF/views/
  suffix: .jsp


upload:
  maxSize: 10240000
  encoding: UTF8

resources:
  - resource:
    url: /static/**
    location: /static/
  - resource:
    url: /css/**
    location: /css/
  - resource:
    url: /js/**
    location: /js/
  - resource:
    url: /images/**
    location: /images/
    
filter:
  # cors server
  cors:
    valid: true
    servers:
      - server:
        allowOrigin: http://localhost:3000/
  
# spring mvc request version
restful:
  version:
    name: content-version
    default: ""
