base:
  jdbc:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hualuomoli?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ""
  
  mybatis:
    mapperLocations: classpath*:mappers/**/*.xml
    basePackage: com.github.hualuomoli
    annotationClass: org.springframework.stereotype.Repository
  